### ISSUE TITLE
Allow credentials to be passed by environment variables.

### ISSUE THREAD

**Issue by jshodd** [FSecureLABS/awspx#12]
Hello there, 

It would be really nice to be able to use a flag in order to have the AWS credentials pulled from environment variables instead of using a profile file. In our case, we use https://github.com/segmentio/aws-okta for credential management. When we execute aws commands locally, aws-okta starts a subshell with the proper credentials in environment variables, so it would be useful to simply use those environment variables to kick off awspx. I am probably going to fork the repo to make this change, but will more than willingly put in a PR here if that's something you would be interested in. I will comment on this issue if I have a working fork in the near future.

Thanks for such a great tool!
Jake

**Comment by 0xdabbad00** [comment]
I had a similar problem of wanting to run `awspx ingest` from an EC2 that has an IAM role associated with it.  My expectation was that the IAM role of the EC2 would be used for the ingestion, but instead it responded with:
```
# awspx ingest
[-] The profile 'default' was not found. Would you like to create it? (y/n) y
AWS Access Key ID [None]:
AWS Secret Access Key [None]:
Default region name [None]:
Default output format [None]:
[+] Profile 'default' created.
[-] Request to establish identity (sts:GetCallerIdentity) failed.
[+] Region set to: eu-west-1
[+] Database set to: default.db
```

I believe AWS tools should just let boto do it's magic in figuring what credentials to use, which in my case would mean hitting the metadata service to get a session of the IAM role.

**Comment by beatro0t** [comment]
@0xdabbad00 Great suggestion - I absolutely agree with you, I'll update the cli to include looking for creds by default.
