### ISSUE TITLE
How long does it take to run?

### ISSUE THREAD

**Issue by mdavis332** [FSecureLABS/awspx#2]
Just curious, I have a fairly simple AWS tenant that I'm testing in. 

I got profile created with 
`awspx profile --create profilename` 
and then ran 
`awspx ingest --profile profilename`.

It has made it to 
```
Resolving actions and resources
[+] Identity based Policy for `arn:aws:iam::aws:policy/AmazonEC2FullAccess` resolved to 351 action(s)
[+] Identity based Policy for `arn:aws:iam::aws:policy/IAMFullAccess` resolved to 694 action(s)
[+] Identity based Policy for `arn:aws:iam::aws:policy/job-function/ViewOnlyAccess` resolved to 142 action(s)
```
and has been sitting there for about 90 minutes with no action. I've already Ctrl+c'd once and restarted and it's sitting at the same place again.

**Comment by beatro0t** [comment]
There are definitely optimizations we should make to that function (Resources are currently stored in a List, a Set would be far better). For a very small environment though, such as the one included in `sample.zip`, it currently takes around 2 mins  - so 90 is definitely on the long side. However, we recently ran it against an environment that had thousands of resources and it only finished after running for an entire day, so it varies.

Would mind running the ingestor with the following args and seeing if there are any improvements? 

```
awspx ingest --profile=profilename--services="IAM,EC2,S3" --except-types "AWS::S3::Object"
```

Identifying the resource on which it is getting stuck would also help. Would you mind adding `print(json.dumps(resource.properties(), indent=2, default=str))` just after the following line and rerunning it: 

https://github.com/FSecureLABS/awspx/blob/136e64a2dc2f4abd931907dcbafe4b14663d4c64/lib/aws/ingestor.py#L666

Be sure to edit `/opt/awspx/lib/aws/ingestor.py` and not the cloned copy if it has been placed elsewhere, as this is the volume mounted by the container (I find myself making this mistake far more often than I would to admit).

Please redact or obfuscate anything that is potentially sensitive from this output before posting it here. For debugging purposes all we really need is the policy construct with a vague idea of resource and condition fields if applicable (account numbers, regions, resource names, etc we can absolutely do without).

**Comment by mdavis332** [comment]
Ooh, very nice, thanks. It was still running about 5 hours later so I'm fairly certain it was hung since it's in a very small AWS env. 

I'm out of pocket most of this weekend, but at some point on Sunday/early Mon I'll try your suggestions and post results.

**Comment by mdavis332** [comment]
Good news: when I got back today the process looks to have completed successfully (I was back to a command prompt and there were more status messages before it returned to a prompt). 

Bad news: something else was using port 80 on the machine and I was unable to use the webUI to browse the results to see what happened. Additionally, this project uses docker in a way I've not encountered before. Rather than being able to setup a docker-compose file with customizable port mappings, everything looks to be hard-coded in the INSTALL file. 

I killed what I thought was using port 80, rerun the INSTALL file and manually reloaded the zip that was created (i made a backup copy of it before reinstall) with an `awspx db --load-zip <name>.zip`. Got a msg that it was successfully loaded, but still can't get to the localhost port 80 in a browser.

I'm going to try to change the hardcoded port exposed to the host in INSTALL and try again. At this point with the docker image being local and built, there may be nothing stopping me from creating a `docker-compose.yml` and setting it up that way. I may just have to look at what the awspx command is doing and pass any cmd manually into the appropriate container.

**Comment by beatro0t** [comment]
That is great news, thank you for the detailed update! I'll begin making some changes to allow port allocations to be a bit more flexible. In the interim, what you can do is change the port in `/opt/awspx/www/package.json`:

https://github.com/FSecureLABS/awspx/blob/136e64a2dc2f4abd931907dcbafe4b14663d4c64/www/package.json#L8

And then restart the container: `docker restart awspx`

Unfortunately, the port wont be exposed on localhost unless you alter your iptables, so its probably easiest to browse the container directly. The following command will give you its ip address:

`
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' awspx
`

Then just browse to this address on the new port you have specified. 

Just as a note, ZIPs will not include attack information, so in order to populate the graph with attack paths, you will need to run `awspx attacks` after the ZIP has been loaded. 

Please let me know if you run into any trouble and if you do happen to create a `compose.yml`, please share it :)

**Comment by beatro0t** [comment]
I've updated `INSTALL` to include a variable for webserver's port:

https://github.com/FSecureLABS/awspx/blob/42d582e2fa368f3f438edd8f5a8254f2847c08b6/INSTALL#L5

Please give it a try by changing it to something that is available and let me know if it resolves the issue.

**Comment by mdavis332** [comment]
> Just as a note, ZIPs will not include attack information, so in order to populate the graph with attack paths, you will need to run awspx attacks after the ZIP has been loaded.

Thanks for that tip! I may have missed that in the documentation. The console output of that cmd is great about letting you know its current progress.

> I've updated INSTALL to include a variable for webserver's port. Please give it a try by changing it to something that is available and let me know if it resolves the issue.

Unfortunately I still can't hit the Vue frontend. This probably has to do with me running this in a Linux VM on my machine that serves as the docker host and, as you mentioned, iptables not setting the rule to allow from my physical host (192.168.1.x) --> Linux VM (192.168.0.x) -->docker network (172.17.0.x). If I curl directly from within the VM, it gets a response but I only have CLI on the linux VM (no JS). Additionally, I can't connect to the IP provided by the `docker inspect` cmd you gave b/c my physical host is on a different network than the docker containers on my Linux VM. So whatever I do has to expose the port on my Linux VM.

If I run this out of a `docker-compose.yml` file and map the port, I can get to the Vue frontend but it's never able to talk to Neo4j b/c it's trying to hit ws://localhost:7687. 
That won't work since in my docker-compose file I tried splitting out the services to have Neo4j run in one container and awspx/Vue frontend in the other. [Dockerfile](https://github.com/mdavis332/awspx/blob/master/Dockerfile) and [docker-compose.yml](https://github.com/mdavis332/awspx/blob/master/docker-compose.yml) example. It looks like the frontend is going to want my physical host to be able to open a websocket directly to the neo4j server if I'm interpreting the message correctly: `can’t establish a connection to the server at ws://neo4j:7687/.`

If that's the case, I'm not sure I could get that to work since I'm browsing from my physical host which will never be able to correctly resolve to a container. Possibly just a limitation of my setup.

I realize we're pretty far down the rabbit hole so if no further ideas, I can close this :)

**Comment by beatro0t** [comment]
I don't think its overly clear in the documentation and its probably something we need to update. :)
So the Vue frontend is only exposed to localhost, if you edit `INSTALL`  and replace all occurrences of `127.0.0.1` with your external IP `192.168.1.x` I imagine it will be accessible (this includes the database). 

You're an absolute legend for putting together those two files! I'm not very familiar with `docker-compose` but just make sure that ports `7374, 7474, and 7867` are also exposed on the neo4j container (they're what's used for db connections and a good test would be to browse to http://neo4j:7474). 

In regard to the websocket error message you are getting, you are interpreting it correctly. You can change the address that is being used here:

https://github.com/FSecureLABS/awspx/blob/42d582e2fa368f3f438edd8f5a8254f2847c08b6/www/src/neo4j.js#L9

Don't worry about closing this issue, if the above doesn't work, there's still a few other things we can try :)

**Comment by mdavis332** [comment]
> You're an absolute legend for putting together those two files!
If I was that good, it would all be working for me ;)

> make sure that ports 7374, 7474, and 7867 are also exposed on the neo4j container
All traffic on all ports should be allowed from the `awspx` container to the `neo4j` container by virtue of the `links` section of `docker-compose.yml` under the `awspx` service. 

> replace all occurrences of 127.0.0.1 with your external IP 192.168.1.x
If I'm understanding correctly, I think the frontend still won't work because of the web socket. 

In my docker-compose attempt, I edited that line to reference the hostname of the container running neo4j:
https://github.com/mdavis332/awspx/blob/310df2deaeb1b61dd9cce30e937747953d85ebd6/www/src/neo4j.js#L9

It gives me the web socket error from my browser I presume b/c my browser is trying to directly open a web socket to bolt://neo4j (rather than the `awspx` container trying to open a web socket to the `neo4j` container, which should work). If my understanding is correct, that won't work for me since my browser on my physical host has no access to the `neo4j` container running inside the Linux VM which is running on my physical host (virtualize _ALL_ the things!).

**Comment by beatro0t** [comment]
Haha :) Ah I see, I'm not familiar with `docker-compose` (had no idea what the links section was). If I'm understanding correctly, what you're saying is that because neo4j isn't directly exposed on your external interface (but rather to the awspx container by some iptable rules as a consequence of the links section), the browser on your hypervisor can'r route there?

I don't know docker-compose well enough to make any suggestions unfortunately but I believe the following will work for you, I've just tested it on a local network: 
```
sed -i 's/127.0.0.1/0.0.0.0/g' /opt/awspx/INSTALL
/opt/awspx/INSTALL
sed -i 's/localhost/192.168.1.x/g' /opt/awspx/www/src/neo4j.js
```

Please give it a shot and let me know :crossed_fingers:

**Comment by mdavis332** [comment]
>  what you're saying is that because neo4j isn't directly exposed on your external interface [...] the browser on your hypervisor can'r route there?

Exactly :)

> sed stuff

Woohoo! That seemed to do the trick, though I had to change `192.168.1.x` to 192.168.0.x` since that's the IP my Linux VM (docker host) is running at (192.168.1.x is my physical hypervisor; virtual switch NATS the VMs to a different subnet). 

Thanks for all the help!
