### ISSUE TITLE
Add support for actions without Resource-Level Permissions

### ISSUE THREAD

**Issue by masteryeets** [FSecureLABS/awspx#21]
At present, awspx only maps actions that support Resource-Level permissions, because of the way it parses the AWS docs to determine which actions affect which resources. However, we may also be interested in actions that don't support Resource-Level permissions. Some of these actions don't affect specific resources (e.g. `s3:ListBuckets`) whereas others do (e.g. `ec2:DescribeInstanceAttribute`). For the sake of expediency, we will treat both cases the same and map all non-RLP actions to a single info node.

**Comment by beatro0t** [comment]
Resolved by c7b96db465220a3cd8627d1c58531059980981b0
