### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by ajinabraham** [FSecureLABS/awspx#3]
Any plans to support mac?

**Comment by beatro0t** [comment]
To be honest, i have no idea - it depends on how hard/easy it is. I'll try and find a mac to test it out on and give you a better answer.

**Comment by leaflyhurley** [comment]
Here are my Mac-compatible changes:
`brew install coreutils`

`diff --git a/INSTALL b/INSTALL
index ae72546..3da4d1b 100755
--- a/INSTALL
+++ b/INSTALL
@@ -6,7 +6,7 @@ WEBPORT="80"

 function install(){

-    MOUNT="/opt/awspx"
+    MOUNT="/Users/my.user/bin/awspx"
     BASE="neo4j"
     DEPS=("docker" "rsync")

@@ -17,10 +17,10 @@ function install(){
              "configparser" "inflect")

     # Ensure script is run as root
-    if [[ "$(whoami)" != "root" ]]; then
-        echo "[-] awspx must be run with root privileges."
-        exit 2
-    fi
+#    if [[ "$(whoami)" != "root" ]]; then
+#        echo "[-] awspx must be run with root privileges."
+#        exit 2
+#    fi

     # Ensure dependencies are met
     for dep in ${DEPS[*]}; do
@@ -45,7 +45,7 @@ function install(){
     # Update
     mkdir -p $MOUNT/data
     rsync -avrt $SOURCE/* ${MOUNT}/. >/dev/null
-    rsync -avrt $0 /bin/awspx >/dev/null
+    rsync -avrt $0 ${MOUNT}/awspx >/dev/null
     echo ""
     set -e

@@ -108,7 +108,8 @@ function awspx(){
     docker exec -it $NAME $DIR/cli.py $@
     }

-if [ "$(systemctl is-active docker)" != "active" ]; then
+#if [ "$(systemctl is-active docker)" != "active" ]; then
+if [[ $(docker info --format '{{json .}}' | jq -r '.ServerErrors' | wc -c) -gt 5 ]]; then
     echo "[-] \"docker\" must first be started."
     exit 2
 fi`

There are definitely more elegant options, like checking the platform then forking to use systemctl or not, but this is quick and dirty.

Note that it's not necessary to remove the root privileges check, I just personally prefer to not run as root and instead scope everything in local directories.

As always, YMMV

**Comment by beatro0t** [comment]
Thank you very much @leaflyhurley! I'll do some testing and update `INSTALL`  later today :)

**Comment by beatro0t** [comment]
I'm going to close this issue. Feel free to reopen it if you run into trouble with `INSTALL` on Mac.

**Comment by artis3n** [comment]
Working for me on OSX 10.14
