### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by efkay88** [FSecureLABS/awspx#32]
Hi awsx-Team,

I am getting the following issue:

`[*] Importing records from /opt/awspx/data/20200616201342551729_default.zip
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 935, in _connect
    s.connect(resolved_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/awspx/cli.py", line 466, in <module>
    main()
  File "/opt/awspx/cli.py", line 461, in main
    args.func(args)
  File "/opt/awspx/cli.py", line 193, in handle_ingest
    handle_db(args)
  File "/opt/awspx/cli.py", line 235, in handle_db
    (success, message) = Neo4j.load(args.load_zip, db)
  File "/opt/awspx/lib/graph/db.py", line 93, in load
    Neo4j.stop()
  File "/opt/awspx/lib/graph/db.py", line 70, in stop
    if not Neo4j.isavailable():
  File "/opt/awspx/lib/graph/db.py", line 43, in isavailable
    auth=(Neo4j.username, Neo4j.password)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 181, in driver
    return cls.bolt_driver(parsed.netloc, auth=auth, **config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 194, in bolt_driver
    return BoltDriver.open(target, auth=auth, **config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/__init__.py", line 357, in open
    pool = BoltPool.open(address, auth=auth, pool_config=pool_config, workspace_config=default_workspace_config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 510, in open
    seeds = [pool.acquire() for _ in range(pool_config.init_size)]
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 510, in <listcomp>
    seeds = [pool.acquire() for _ in range(pool_config.init_size)]
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 523, in acquire
    return self._acquire(self.address, timeout)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 395, in _acquire
    connection = self.opener(address, timeout)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 507, in opener
    return Bolt.open(addr, auth=auth, timeout=timeout, **pool_config)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 195, in open
    keep_alive=pool_config.keep_alive,
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 1055, in connect
    raise last_error
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 1045, in connect
    s = _connect(resolved_address, timeout, keep_alive)
  File "/usr/local/lib/python3.7/dist-packages/neo4j/io/__init__.py", line 949, in _connect
    raise ServiceUnavailable("Failed to establish connection to {!r} (reason {})".format(resolved_address, error))
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to IPv6Address(('::1', 7687, 0, 0)) (reason [Errno 99] Cannot assign requested address)`

I have tried to start the container with a different port but no idea why IPv6 instead 127.0.0.1 is used. Any idea how this can be changed?

Thanks!

**Comment by beatro0t** [comment]
Hi @efkay88, thanks for logging the issue.

That is very odd and I'm unsure why it is trying to use IPv6, its not something I've seen before. If you open `/opt/awspx/lib/graph/db.py`, can you confirm the connection string looks like this? 

https://github.com/FSecureLABS/awspx/blob/8e377f196d17595440b22d63eccdd933f5a0a02e/lib/graph/db.py#L13

And if you check the containers hosts file (e.g. `docker exec -it awspx cat /etc/hosts`), is the first entry for `localhost` an IPv4 address, e.g:

```
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
...
```
If this is true in both cases, we're going to need to do a bit more debugging. If not, try making the changes and run `awspx db --load-zip 20200616201342551729_default.zip` to check whether this resolves the issue (i.e. it will either throw the same error or complete successfully). 

You mentioned you tried to start the container with a different port. Was that by making changes to `INSTALL`? If so, would you mind sending me a redacted version of the changes so I can try to recreate the issue this side, along with the operating system you are using, as well as any kernel security modules that are active.

**Comment by efkay88** [comment]
Thanks a lot for the quick response!

The connection string was same as you pointed. I have modified it from localhost to 127.0.0.1
but that still ends up in a similar issue.  For some reason I cannot connect to the service... I will try to investigate later more. But in meanwhile here is some information, maybe you see something that I am missing :/ 

```
neo4j.exceptions.ServiceUnavailable: Failed to establish connection to IPv4Address(('127.0.0.1', 7687)) (reason [Errno 111] Connection refused) ```

```db1b79e7c6b2        neo4j:3.5.13        "/sbin/tini -g -- /d…"   About an hour ago   Up 41 minutes       127.0.0.1:7373->7373/tcp, 127.0.0.1:7474->7474/tcp, 127.0.0.1:7687->7687/tcp, 7473/tcp, 127.0.0.1:8066->80/tcp   awspx
```
I changed the port from 80 to 8099 in the INSTALL file. This did not have any affect. 
nc localhost 80 (or 8099) 

```
$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8066          0.0.0.0:*               LISTEN      39197/docker-proxy  
tcp        0      0 127.0.0.1:7687          0.0.0.0:*               LISTEN      39210/docker-proxy  
tcp        0      0 127.0.0.1:7373          0.0.0.0:*               LISTEN      39236/docker-proxy  
tcp        0      0 127.0.0.1:7474          0.0.0.0:*               LISTEN      39224/docker-proxy  
```

```
$ telnet 127.0.0.1 8066
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
``` (same for port 7687)

```
$ uname -a
Linux 5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux

$ docker --version
Docker version 19.03.11, build 42e35e61f3
```

Thanks for your support!

**Comment by beatro0t** [comment]
Its an absolute pleasure, thank you for all the detailed information! 

So funnily enough, I ran into the issue very soon after responding this morning :see_no_evil:  It looks like the changes we made yesterday broke some things. I've just pushed a hotfix, would you mind giving it a try and see if it resolves the issue?  You should be able to just run: `awspx update` - if it fails please let me know. 

As for the `WEBPORT` changes, it looks like it is succeeding based on the telnet excerpt (I'm assuming you meant port 8066 and 8099 is a typo, please correct me if I am misunderstanding you). If you browse to http://localhost:8066 does the page load?

**Comment by efkay88** [comment]
done! It works! (and yes it was a typo :) )
