### ISSUE TITLE
Couldn't access 127.0.0.1 on Mac due to docker-machine using 192.168.99.100

### ISSUE THREAD

**Issue by alexdaviestray** [FSecureLABS/awspx#36]
Hey, this isn't really a bug, more of a config issue that might be worth documenting to help others.

**OS** 
MacOS Catalina 10.15.6

**Issue** 
After launching the awspx docker container using docker-machine with the default settings I was unable to access the web services on localhost.

**Remediation**
Docker-machine and docker toolbox use 192.168.99.100 instead of localhost. I had to modify the docker run command to use 0.0.0.0 instead of 127.0.0.1:

-p 0.0.0.0:80:80 \
-p 0.0.0.0:7687:7687 \
-p 0.0.0.0:7373:7373 \
-p 0.0.0.0:7474:7474 \

Once changed I was able to access the interface here http://192.168.99.100.

Hopefully this will help other folks.

**Comment by beatro0t** [comment]
Hi @alexdaviestray, thanks for this! 

I've updated the documentation to try clarify things a bit better for more general cases (e.g. https://github.com/FSecureLABS/awspx/wiki/FAQs#how-do-i-remotely-access-the-web-interface). Please let me know if you feel this covers it, or if there's additional information we should include.
