### ISSUE TITLE
Issues when using podman on fedora 33

### ISSUE THREAD

**Issue by unsubtleguy** [FSecureLABS/awspx#43]
When using Fedora 33 and podman, the INSTALL script doesn't consider selinux, and the container won't be able to write to /opt/awspx

I changed the mount options to include the ":z" suffix, which relabeled the directory and the container could write to it.

I.e. `-v $(MOUNT)/data:/opt/awspx:z`

**Comment by beatro0t** [comment]
Hey @unsubtleguy, sorry about the delay in getting back to you. Thanks for this, I had no idea! Please feel free to submit a PR so i can credit you, otherwise I will happily commit the change
