### ISSUE TITLE
Neo4j connection error : client unauthorized

### ISSUE THREAD

**Issue by kapshure** [FSecureLABS/awspx#5]
If I use the sample.zip or run through 'awspx ingest' (which does successfully connect and pull down env data after I plug in Key/Secret), when I try to go to browser ( I did edit 'INSTALL' to support a different web port + eth0 IP, so I could access remotely), I am getting this error:

"Neo4jError: the client is unauthorized due to authentication failure"

I only have limited experience w/neo4j, but I can't figure out how to properly connect into the front-end of this tool. I am able to go to the IP:7474, and upon connecting, I actually see some data related to my AWS environment -- so I must not be too far off.  I changed the default web port to 8080, I know this is operator error :)   any nudge or help is appreciated

**Comment by beatro0t** [comment]
Hi @kapshure, thank you for reporting this issue and for providing such detailed information - the error was mine :). I have  managed to recreate it and will push a fix shortly. In the interim, could you modify the following to reflect the IP address you made use of in INSTALL and let me know if this resolves the issue: 

https://github.com/FSecureLABS/awspx/blob/5b832c2f8abcfbe4e01a08f5195810062309a946/www/src/neo4j.js#L9
